### ISSUE TITLE
Criar um define para cada prioridade

### ISSUE THREAD

**Issue by eduardomarossi** [CaioFauza/APS1Embarcados#1]
https://github.com/CaioFauza/MonophonyMusic/blob/3fc755ba624a5459472457fd819c1da3640d29cc/src/main.c#L100-L107

Exemplo
```
// (Colocar este define junto com os outros do botão)
#define BUT2_PRIORITY 6

NVIC_SetPriority(BUT2_PIO_ID, BUT2_PRIORITY);
```

Vantagens:
- Fica explicito junto com as demais configurações do botão, permitindo fácil alteração da prioridade se necessário.
- Evita número "mágico" no meio do código, ficando bem óbvio o que se trata (código se auto documenta).

**Comment by caiofauza** [comment]
Commit: https://github.com/CaioFauza/MonophonyMusic/commit/e92a957c12da8424e46af3d5b60c313e53787732
