### ISSUE TITLE
Poderia ter uma função draw_music_title

### ISSUE THREAD

**Issue by eduardomarossi** [CaioFauza/APS1Embarcados#2]
https://github.com/CaioFauza/MonophonyMusic/blob/3fc755ba624a5459472457fd819c1da3640d29cc/src/main.c#L135

Que tal?

```
void draw_music_title(char* status) {
    gfx_mono_draw_string(status, 50,16, &sysfont);
}
```

Vantagens:
- Separa lógica de processamento da lógica de exibição.
- Para alterar a interface visual no OLED, basta alterar uma função, ficando bem claro, o seu uso. Evitando ter código repetido espalhado.

**Comment by caiofauza** [comment]
Commit: https://github.com/CaioFauza/MonophonyMusic/commit/d0e50a42a155bf505d2efed57c576ffb72b55956
